version: "3"
services:

  otel-collector:
    container_name: otel-collector-validadorjwt
    image: otel/opentelemetry-collector-contrib:0.95.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/otel-collector-config.yaml
    volumes:
      - ./cfg/otel-collector-config.yaml:/etc/otelcol-contrib/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
      - zipkin
  
  prometheus:
    container_name: prometheus-validatorjwt
    image: prom/prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./cfg/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  
  grafana:
    container_name: grafana-validadorjwt
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"

  jaeger:
    container_name: jaeger-validadorjwt
    image: jaegertracing/all-in-one
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
      - "4317"

  zipkin:
    container_name: zipkin-validadorjwt
    image: openzipkin/zipkin
    restart: always
    ports:
      - "9411:9411"
