spring:
  application:
    name: validadorjwt
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/swagger.html
constraints:
  jwt:
    validador: basicJwtValidator
    tamanhomaximo: 1000
  name:
    validador: namePortuguesValidator
    tamanhomaximo: 256
  seed:
    validador: integerLimitSeedValidator
    valormaximo: 2147483647
  claims:
    validador: defaultClaimsValidator
  role:
    validador: defaultStringRoleValidator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution.percentiles-histogram.http.server.requests: true
    tags:
      application: validadorjwt
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
otel:
  endpoint: http://localhost:4317