{
 "title": "Validador JWT - Requisições HTTP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Resumo requisições HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requisições por segundo",
   "type": "timeseries",
   "description": "Quantidade média de requisições por segundo",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method,uri,status) (rate(http_server_requests_milliseconds_count{uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}: {{status}}"
    }
   ]
  },
  {
   "title": "Duração das requisições",
   "type": "timeseries",
   "description": "Tempo médio das requisições HTTP",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (status,uri,method) (rate(http_server_requests_milliseconds_sum{uri!=\"/actuator/prometheus\"}[1m]))\r\n/\r\nsum by (status,uri,method) (rate(http_server_requests_milliseconds_count{uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}: {{status}}"
    }
   ]
  },
  {
   "title": "Quantitativo de status dos responses",
   "type": "piechart",
   "description": "Quantitativo dos status response das requisições",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "http_server_requests_milliseconds_count{uri!=\"/actuator/prometheus\"}",
     "legendFormat": "{{method}} {{uri}}: {{status}}"
    }
   ]
  },
  { "title": "Resumo logs da aplicação", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "ERROR logs",
   "type": "timeseries",
   "description": "Quantidade de logs do tipo ERROR",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (level) (logback_events_total{uri!=\"/actuator/prometheus\", job=\"otel-collector\", level=\"error\"} - logback_events_total{uri!=\"/actuator/prometheus\", job=\"otel-collector\", level=\"error\"} offset 1m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "timeseries",
   "description": "Quantidade de logs do tipo WARN",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (level) (logback_events_total{uri!=\"/actuator/prometheus\", job=\"otel-collector\", level=\"warn\"} - logback_events_total{uri!=\"/actuator/prometheus\", job=\"otel-collector\", level=\"warn\"} offset 1m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "INFO logs",
   "type": "timeseries",
   "description": "Quantidade de logs do tipo INFO",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (level) (logback_events_total{uri!=\"/actuator/prometheus\", job=\"otel-collector\", level=\"info\"} - logback_events_total{uri!=\"/actuator/prometheus\", job=\"otel-collector\", level=\"info\"} offset 1m)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}